create table presenca (data_entrada date not null, data_saida date, horario_entrada time(6) not null, horario_saida time(6), id bigint not null auto_increment, usuario_id bigint not null, primary key (id)) engine=InnoDB;
create table usuario (id bigint not null auto_increment, documento varchar(11) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists usuario add constraint UKsqdsrgo7yd5nlfxh382v44rj9 unique (documento);
alter table if exists presenca add constraint FKjljnokxwvxeoikr7nmc9gyr7s foreign key (usuario_id) references usuario (id);
create table presenca (data_entrada date not null, data_saida date, horario_entrada time(6) not null, horario_saida time(6), id bigint not null auto_increment, usuario_id bigint not null, primary key (id)) engine=InnoDB;
create table usuario (id bigint not null auto_increment, documento varchar(11) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists usuario add constraint UKsqdsrgo7yd5nlfxh382v44rj9 unique (documento);
alter table if exists presenca add constraint FKjljnokxwvxeoikr7nmc9gyr7s foreign key (usuario_id) references usuario (id);
create table presenca (data_entrada date not null, data_saida date, horario_entrada time(6) not null, horario_saida time(6), id bigint not null auto_increment, usuario_id bigint not null, primary key (id)) engine=InnoDB;
create table usuario (id bigint not null auto_increment, documento varchar(11) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists usuario add constraint UKsqdsrgo7yd5nlfxh382v44rj9 unique (documento);
alter table if exists presenca add constraint FKjljnokxwvxeoikr7nmc9gyr7s foreign key (usuario_id) references usuario (id);
create table presenca (data_entrada date not null, data_saida date, horario_entrada time(6) not null, horario_saida time(6), id bigint not null auto_increment, usuario_id bigint not null, primary key (id)) engine=InnoDB;
create table usuario (id bigint not null auto_increment, documento varchar(11) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists usuario add constraint UKsqdsrgo7yd5nlfxh382v44rj9 unique (documento);
alter table if exists presenca add constraint FKjljnokxwvxeoikr7nmc9gyr7s foreign key (usuario_id) references usuario (id);
INSERT INTO usuario (documento, nome) VALUES ('12345678901', 'João Silva');
INSERT INTO usuario (documento, nome) VALUES ('98765432109', 'Maria Oliveira');
INSERT INTO usuario (documento, nome) VALUES ('45678912345', 'Carlos Souza');
INSERT INTO presenca (data_entrada, horario_entrada, usuario_id) VALUES ('2023-10-01', '08:00:00', 1);
INSERT INTO presenca (data_entrada, horario_entrada, data_saida, horario_saida, usuario_id) VALUES ('2023-10-01', '08:00:00', '2023-10-01', '17:00:00', 1);
INSERT INTO presenca (data_entrada, horario_entrada, usuario_id) VALUES ('2023-10-01', '09:00:00', 2);
INSERT INTO presenca (data_entrada, horario_entrada, data_saida, horario_saida, usuario_id) VALUES ('2023-10-02', '08:30:00', '2023-10-02', '18:00:00', 2);
INSERT INTO presenca (data_entrada, horario_entrada, usuario_id) VALUES ('2023-10-01', '07:45:00', 3);
INSERT INTO presenca (data_entrada, horario_entrada, data_saida, horario_saida, usuario_id) VALUES ('2023-10-02', '08:15:00', '2023-10-02', '17:30:00', 3);
